name: PR
on: pull_request

# Using 16MB stacks for deep test/debug recursion
env:
  RUST_MIN_STACK: 16777216

jobs:

  check:
    name: Check (1.63.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.63.0
      - run: cp ci/compat-Cargo.lock ./Cargo.lock
      - run: cargo check --verbose --locked

  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
      - run: cargo test --verbose --package rayon
      - run: cargo test --verbose --package rayon-core
      - run: ./ci/highlander.sh

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.72.1
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  ci-success:
    name: Complete
    runs-on: ubuntu-latest
    needs: [check, test, fmt]
    steps:
      - run: exit 0
  ci-failed:
    name: Complete
    runs-on: ubuntu-latest
    needs: [check, test, fmt]
    if: failure()
    steps:
      - run: exit 1
